#version 450 core

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer Positions
{
	vec2 positions[];
};

layout(std430, binding = 1) buffer Velocities
{
	vec2 velocities[];
};

uniform float dt;
uniform int numParticles;
uniform float speed;

void main()
{
	uint id = gl_GlobalInvocationID.x;

	if (id >= numParticles)
	{
		return;
	}

	positions[id] += velocities[id] * speed * dt;
}